DROP DATABASE LIBRARY;
CREATE DATABASE LIBRARY;
USE LIBRARY;

CREATE TABLE BRANCH(
    BID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(40),
    Location VARCHAR(200)
);

CREATE TABLE PUBLISHER(
    Publisher_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Publisher_Name VARCHAR(40),
    Address varchar(200)
);

CREATE TABLE DOCUMENT(
    Doc_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(40),
    PDate DATE,
    Publisher_ID INTEGER,
    CONSTRAINT DOCUMENT_PUBLISHER FOREIGN KEY (Publisher_ID) REFERENCES PUBLISHER(Publisher_ID)
);

CREATE TABLE DOC_COPY(
    UUID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Doc_ID INTEGER NOT NULL,
    Copy_No INTEGER NOT NULL,
    Branch_ID INTEGER NOT NULL,
    CONSTRAINT DCOPY_DOCUMENT FOREIGN KEY (Doc_ID) REFERENCES DOCUMENT(Doc_ID),
    CONSTRAINT DCOPY_BRANCH FOREIGN KEY (Branch_ID) REFERENCES BRANCH(BID)
);

CREATE TABLE PERSON(
    PID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PName VARCHAR(40)
);

CREATE TABLE PROCEEDINGS(
    Doc_ID INTEGER PRIMARY KEY,
    Date DATE,
    Location VARCHAR(200),
    CONSTRAINT PROCEEDINGS_DOCUMENT FOREIGN KEY (Doc_ID) REFERENCES DOCUMENT(Doc_ID)
);

CREATE TABLE CHAIRS(
    Doc_ID INTEGER NOT NULL,
    PID INTEGER NOT NULL,
    CONSTRAINT PRIMARY_KEY PRIMARY KEY(Doc_ID, PID),
    CONSTRAINT CHAIRS_DOCUMENT FOREIGN KEY(Doc_ID) REFERENCES DOCUMENT(Doc_ID),
    CONSTRAINT CHAIRS_PERSON FOREIGN KEY(PID) REFERENCES PERSON(PID)
);

CREATE TABLE JOURNAL_VOLUME(
    JID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Doc_ID INTEGER NOT NULL,
    Volume_NO INTEGER NOT NULL,
    Editor INTEGER NOT NULL,
    CONSTRAINT JVOLUME_DOCUMENT FOREIGN KEY(Doc_ID) REFERENCES DOCUMENT(Doc_ID),
    CONSTRAINT JVOLUME_PERSON FOREIGN KEY(Editor) REFERENCES PERSON(PID)
);

CREATE TABLE JOURNAL_ISSUE(
    Volume INTEGER NOT NULL,
    Scope VARCHAR(500),
    Issue_NO INTEGER NOT NULL,
    CONSTRAINT PRIMARY_KEY PRIMARY KEY(Volume, Issue_NO),
    CONSTRAINT JISSUE_JVOLUME FOREIGN KEY(Volume) REFERENCES JOURNAL_VOLUME(JID)
);

CREATE TABLE GUEST_EDITORS(
    Volume INTEGER NOT NULL,
    Issue_NO INTEGER NOT NULL,
    GEditor INTEGER NOT NULL,
    CONSTRAINT PRIMARY_KEY PRIMARY KEY(Volume, Issue_NO, GEditor),
    CONSTRAINT GEDITORS_JVOLUME FOREIGN KEY (Volume) REFERENCES JOURNAL_VOLUME(JID),
    CONSTRAINT GEDITORS_PERSON FOREIGN KEY(GEditor) REFERENCES PERSON(PID)
);

CREATE TABLE BOOK(
    Doc_ID INTEGER NOT NULL PRIMARY KEY,
    ISBN INTEGER NOT NULL,
    CONSTRAINT BOOK_DOCUMENT FOREIGN KEY(Doc_ID) REFERENCES DOCUMENT(Doc_ID)
);

CREATE TABLE AUTHOR(
    PID INTEGER NOT NULL,
    Doc_ID INTEGER NOT NULL,
    CONSTRAINT PRIMARY_KEY PRIMARY KEY(PID, Doc_ID),
    CONSTRAINT AUTHOR_PERSON FOREIGN KEY(PID) REFERENCES PERSON(PID),
    CONSTRAINT AUTHOR_DOCUMENT FOREIGN KEY(Doc_ID) REFERENCES DOCUMENT(Doc_ID)
);

CREATE TABLE READER(
    Reader_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Type VARCHAR(20) NOT NULL,
    Name VARCHAR(20) NOT NULL,
    Address VARCHAR(200),
    Phone_NO CHAR(10),
    CONSTRAINT CHK_PHONE CHECK (Phone_NO not like '%[^0-9]%')
);

CREATE TABLE BORROWS(
    Borrow_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Doc_Detail INTEGER NOT NULL,
    Reader_ID INTEGER NOT NULL,
    BDTime DATE NOT NULL,
    RDTime DATE,
    CONSTRAINT BORROWS_READER FOREIGN KEY(Reader_ID) REFERENCES READER(Reader_ID),
    CONSTRAINT BORROWS_DCOPY FOREIGN KEY(Doc_Detail) REFERENCES DOC_COPY(UUID)
);

CREATE TABLE RESERVES(
    Reserve_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Reader_ID INTEGER NOT NULL,
    Doc_Detail INTEGER NOT NULL,
    DTime DATE NOT NULL,
    CONSTRAINT RESERVE_READER FOREIGN KEY(Reader_ID) REFERENCES READER(Reader_ID),
    CONSTRAINT RESERVE_DCOPY FOREIGN KEY(Doc_Detail) REFERENCES DOC_COPY(UUID)
);

INSERT INTO BRANCH(Name, Location) VALUES
();

INSERT INTO PUBLISHER(Publisher_Name, Address) VALUES
();

INSERT INTO DOCUMENT(Title, PDate, Publisher_ID) VALUES
();

INSERT INTO DOC_COPY(Doc_ID, Copy_No, Branch_ID) VALUES
();

INSERT INTO PERSON(PNAME) VALUES
();

INSERT INTO PROCEEDINGS(Doc_ID, Date, Location) VALUES
();

INSERT INTO CHARIS(Doc_ID, PID) VALUES
();

INSERT INTO JOURNAL_VOLUME(Doc_ID Volume_NO, Editor) VALUES
();

INSERT INTO JOURNAL_ISSUE(Volume, Scope, Issue_NO) VALUES
();

INSERT INTO GUEST_EDITORS(Volume, Issue_NO, GEditor) VALUES
();

INSERT INTO BOOK(Doc_ID, ISBN) VALUES
();

INSERT INTO AUTHOR(PID, Doc_ID) VALUES
();

INSERT INTO READER(Type, Name, Address, Phone_NO) VALUES
();

INSERT INTO BORROWS(Doc_Detail, Reader_ID, BDTime, RDTime) VALUES
();

INSERT INTO RESERVES(Reader_ID, Doc_Detail, DTime) VALUES
();